spring.application.name=jbell_backend


# 서버 포트 설정
server.port=8080

#리소스 매핃 설정
spring.web.resources.add-mappings=false

#DB 설정
# Dependency required: org.bgee.log4jdbc-log4j2:log4jdbc-log4j2-jdbc4.1
spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.datasource.url=jdbc:log4jdbc:mysql://141.147.158.244:3306/jbelldb?serverTimezone=Asia/Seoul&useUnicode=true&character_set_sever=utf8mb4
spring.datasource.username=ksmart57id
spring.datasource.password=ksmart57pw

# mybatis 설정
mybatis.mapper-locations=classpath:mapper/**/*.xml

# 로그파일 설정
logging.config=classpath:logback-spring.xml