spring.application.name=jbell_backend


# 서버 포트 설정
server.port=8080

#리소스 매핃 설정
spring.web.resources.add-mappings=false

#DB 설정
# Dependency required: org.bgee.log4jdbc-log4j2:log4jdbc-log4j2-jdbc4.1
spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.datasource.url=jdbc:log4jdbc:mysql://141.147.158.244:3306/jbelldb?serverTimezone=Asia/Seoul&useUnicode=true&character_set_sever=utf8mb4
spring.datasource.username=ksmart57id
spring.datasource.password=ksmart57pw

# Mail Server Settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=wjsdnsgh0206@gmail.com
spring.mail.password=yzjsjbnelznzrmqd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true




# mybatis 설정
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

# 로그파일 설정
logging.config=classpath:logback-spring.xml

#============================================================
# 외부 api 공통 설정값
#============================================================
external.api.timeout=15000

#============================================================
# 공공데이터 data.go.kr 설정값
#============================================================
publicdata.servicekey=2e572cb46f96a219ef27c211707e7875f4791d19b01a025e64cab130ec2cfcc1

#============================================================
# 재난안전데이터공유플랫폼 safetydata.go.kr 설정값
#============================================================
safetydata.servicekey=67IG7XH459E6WK55
#행정안전부_자연재난국민행동요령 (20588)
safetydata.behaviorMethod.natural.servicekey=815MBNVNZAN56XF8
#행정안전부_사회재난국민행동요령 (20589)
safetydata.behaviorMethod.social.servicekey=W5HH5B5DAY9A1511
#행정안전부_생활안전국민행동요령 (20590)
safetydata.behaviorMethod.life.servicekey=27PYU6FK29DCNI44




# 특보코드조회
safetydata.kma.weather.warning.key=2e572cb46f96a219ef27c211707e7875f4791d19b01a025e64cab130ec2cfcc1


# 지진 특보 api -- 사용 (최지영)
# 요청 예시
# 지진 https://apihub.kma.go.kr/api/typ01/url/eqk_now.php?tm=201311231215&disp=0&help=1&authKey=ZoicmoeHTrWInJqHhw61_g
safetydata.kma.disaster.earthquake.key=ZoicmoeHTrWInJqHhw61_g

# 태풍 발생 https://apihub.kma.go.kr/api/typ01/url/typ_lst.php?YY=2012&disp=0&help=1&authKey=ZoicmoeHTrWInJqHhw61_g
# 태풍 이동 경로 https://apihub.kma.go.kr/api/typ01/url/typ_data.php?YY=2011&typ=9&seq=8&mode=1&disp=0&help=1&authKey=ZoicmoeHTrWInJqHhw61_g
safetydata.kma.disaster.typhoon.key=ZoicmoeHTrWInJqHhw61_g

# 산불위험예보정보
safetydata.forest.fire.hazard.key=2e572cb46f96a219ef27c211707e7875f4791d19b01a025e64cab130ec2cfcc1
# 산사태 예보발령
safetydata.forest.landslide.warning.key=2e572cb46f96a219ef27c211707e7875f4791d19b01a025e64cab130ec2cfcc1

# 행정안전부_침수흔적도 -- 사용 (최지영)
# 행정안전부_침수흔적도    최신조회 요청 없음 + 데이터 갱신 2025-06-04에서 멈춤
# 제공 사이트 : https://www.safetydata.go.kr/disaster-data/view?dataSn=108
# 요청 주소 예시 : https://www.safetydata.go.kr/V2/api/DSSP-IF-00117?serviceKey=O132YQL4IWL7N7MK&numOfRows=1&pageNo=1&returnType=json
# 갱신주기 1일, REST, JSON
safetydata.mois.flood.trace.key=O132YQL4IWL7N7MK

# 재난문자
safetydata.disaster.msg.key=EM8VJ3SD0T2YCFFR
# 기상청 특보
safetydata.weatherWarning.key=67IG7XH459E6WK55








# 행정안전부_이재민 임시주거시설
# 제공 사이트 : https://www.safetydata.go.kr/disaster-data/view?dataSn=1341
# 요청 주소 예시 : https://www.safetydata.go.kr/V2/api/DSSP-IF-10945?serviceKey=3GHRW69P7QEQBGMT&numOfRows=1&pageNo=1&returnType=json
# 갱신주기 1일, REST, JSON
safetydata.shelter.mois.temporary.key=3GHRW69P7QEQBGMT


# 행정안전부_무더위쉼터
# 제공 사이트 : https://www.safetydata.go.kr/disaster-data/view?dataSn=1338
# 요청 주소 예시 : https://www.safetydata.go.kr/V2/api/DSSP-IF-10942?serviceKey=B46160KXPEO76640&numOfRows=1&pageNo=1&returnType=json
# 갱신주기 1일, REST, JSON
safetydata.shelter.mois.heat.key=B46160KXPEO76640


# 한파쉼터
# 제공 사이트 : https://www.safetydata.go.kr/disaster-data/view?dataSn=966
# 요청 주소 예시 : https://www.safetydata.go.kr/V2/api/DSSP-IF-10804?serviceKey=Z5SKGB47241A8DAC&numOfRows=1&pageNo=1&returnType=json
# 갱신주기 1일, REST, JSON
safetydata.shelter.mois.cold.key=Z5SKGB47241A8DAC

# 행정안전부_지진옥외대피장소
# 제공 사이트 : https://www.safetydata.go.kr/disaster-data/view?dataSn=1339
# 요청 주소 예시 : https://www.safetydata.go.kr/V2/api/DSSP-IF-10943?serviceKey=0DV6Z4SNNN8O5403&numOfRows=1&pageNo=1&returnType=json
# 갱신주기 1일, REST, JSON
safetydata.shelter.mois.earthquake.key=0DV6Z4SNNN8O5403



# 민방위대피소_KINS_원자력안전사고
# 제공 사이트 : https://www.safetydata.go.kr/disaster-data/view?dataSn=1189
# 요청 주소 예시 : https://www.safetydata.go.kr/V2/api/DSSP-IF-10417?serviceKey=8J0C1EZD0148CI3L&numOfRows=1&pageNo=1&returnType=json
# 갱신주기 1일, REST, JSON
safetydata.shelter.kins.nuclear.key=8J0C1EZD0148CI3L

# 행정안전부_민방위_대피소_재난통합
# 제공 사이트 : https://www.safetydata.go.kr/disaster-data/view?dataSn=184
# 요청 주소 예시 : https://www.safetydata.go.kr/V2/api/DSSP-IF-00195?serviceKey=616SG7EF4F8BTN93&numOfRows=1&pageNo=1&returnType=json
# 갱신주기 30분, REST, JSON
safetydata.shelter.mois.civil.defense.key=616SG7EF4F8BTN93














#============================================================
# openweather api api.openweathermap.org 설정값
#============================================================
openweather.servicekey=75417221f6cc71ddcab1eb8beedd8d8a

#============================================================
# 기상청API 허브 apihub.kma.go.kr 설정값
#============================================================
apihubdata.servicekey=ZoicmoeHTrWInJqHhw61_g